apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-archive
spec:
  workspaces:
    - name: source
  params:
    - name: source_dir
      description: Location of image to be patched with
      type: string
      default: "."
    - name: url
      description: Location of image to be patched with
      type: string

  steps:
    - name: get-archive
      image: registry.redhat.io/ubi8/ubi
      workingDir: /workspace/source

      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: artifactory-auth
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: artifactory-auth
              key: password
        - name: SECRET_URL
          valueFrom:
            secretKeyRef:
              name: artifactory-auth
              key: url

      command: ["/bin/bash", "-c"]
      args:
        - |-
          cd $(inputs.params.source_dir)
          curl -k -u "${SECRET_USERNAME}:${SECRET_PASSWORD}" \
            -O "${SECRET_URL}/artifactory/aspnet-core-artifacts/ContosoTeamStats/$(inputs.params.url)" 

          tar xzf "$(inputs.params.url)"

