apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  # thin/csi-sc
  storageClassName: ocs-storagecluster-ceph-rbd
  # Block/Filesystem
  volumeMode: Filesystem
  # ReadWriteOnce/ReadWriteMany
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
