apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aspnet-core-app
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dotnet-gitops
  project: default
  source:
    path: quickstart/aspnet-core/deploy/overlays/argo
    repoURL: https://github.com/kskels/azure-cache-redis-samples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
