apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: redhat-registry-auth
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.redhat.io": {
          "auth": "base64-encoded-auth-token"
        }
      }
    }
