apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  storageClassName: "<block-storage-class>"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
