apiVersion: v1
kind: Secret
metadata:
  name: gitlab-com-secret
  annotations:
    tekton.dev/git-0: https://gitlab.kskels.com
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: gitlab-personal-access-token
